export const DASHBOARD_ACTION_TYPES = {
  SET_COLLECTION: 'dashboard/SET_COLLECTION',
  ADD_CHART: 'dashboard/ADD_CHART',
  UPDATE_CHART: 'dashboard/UPDATE_CHART',
  REMOVE_CHART: 'dashboard/REMOVE_CHART',
  DUPLICATE_CHART: 'dashboard/DUPLICATE_CHART',
  SET_SELECTED_CHART: 'dashboard/SET_SELECTED_CHART',
  SET_LAYOUTS: 'dashboard/SET_LAYOUTS',
  UPDATE_CHART_LAYOUT: 'dashboard/UPDATE_CHART_LAYOUT',
  LOAD_DASHBOARD: 'dashboard/LOAD_DASHBOARD',
  RESET_DASHBOARD: 'dashboard/RESET_DASHBOARD',
};
